name: CD - Deploy to Railway

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to Railway
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Railway
              uses: railwayapp/railway-github-action@main
              with:
                  service: 'fastapi-service'
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
