name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to AWS EC2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to EC2
              env:
                  AWS_HOST: ${{ secrets.AWS_HOST }}
                  AWS_USER: ${{ secrets.AWS_USER }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > private_key.pem
                  chmod 600 private_key.pem
                  ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
                    cd ~/fastapi-book-project
                    git pull origin main
                    source venv/bin/activate
                    pip install -r requirements.txt
                    sudo systemctl restart fastapi
                  EOF
